---
# ansible-playbook sample
# usage: ansible-playbook sample_vars.yaml --extra-vars "service_name=myname work_space=${WORKSPACE}"

- hosts: www-test-java
  vars: 
    service_name: "myname"
    run_dir: "mydir"
    work_space: "/data/home/jenkins/.jenkins/workspace/sample"
    script_name: "jenkins_reboot.sh"
  remote_user: java
  tasks:

  - name:  pause service
    shell: CURRENT_SERVICE_NAME={{service_name}} ./service_mesh_api.sh pause

  - name: Copy war  file to client
    copy: src={{work_space}}/target.tar.gz dest=~/{{run_dir}}

  - name: extract target.tar.gz
    shell:  tar -C ~/{{run_dir}} -xvzf ~/{{run_dir}}/target.tar.gz

  - name: sleep 5
    shell:  sleep 5

  - name:  stop java
    shell: ./{{script_name}} stop
    register: outMessg

  - debug: var=outMessg.stdout_lines
    ignore_errors: True

  - name: bakckup old package
    shell: ./{{script_name}} backup
    ignore_errors: True

  - name: delete old package
    shell: rm -rf ~/{{run_dir}}/*.jar
    ignore_errors: True

  - name: mv package
    shell:  mv -f ~/{{run_dir}}/target/*.jar  ~/{{run_dir}}

  - name: start java
    shell: ./{{script_name}} restart

  - shell: ps -eo pid,cmd,etime,stime | grep java
    register: ps

  - debug: var=ps.stdout_lines

  - name: Clean target.tar.gz
    shell:  rm -rf ~/{{run_dir}}/target*
    ignore_errors: True

  - name: sleep 10
    shell:  sleep 10

  - name:  resume service
    shell: CURRENT_SERVICE_NAME={{service_name}} ./service_mesh_api.sh resume
